service: jedeschule

frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  environment:
    FEED_BUCKET_NAME: !Ref ScraperFeedBucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: !Sub
        - "arn:aws:s3:::#{BucketName}/*"
        - BucketName: !Ref ScraperFeedBucket

resources:
  - AWSTemplateFormatVersion: "2010-09-09"
    Transform: "AWS::Serverless-2016-10-31"
  - ${file(./s3-template.yml)}

functions:
  hello:
    handler: handler.hello
  lambdaScrape:
    handler: launcher.scrape
    events:
      - schedule:
          name: Scrape_Hamburg
          rate: cron(0 6 * * ? *)  # 06:00
          input:
            spider_name: "hamburg"
      - schedule:
          name: Scrape_Hessen
          rate: cron(0 7 * * ? *)  # 07:00
          input:
            spider_name: "hessen"
      - schedule:
          name: Scrape_Sachsen-Anhalt
          rate: cron(0 14 * * ? *)  # 14:00
          input:
            spider_name: "sachsen-anhalt"
      - schedule:
          name: Scrape_Schleswig-Holstein
          rate: cron(0 15 * * ? *)  # 15:00
          input:
            spider_name: "schleswig-holstein"
      - schedule:
          name: Scrape_Thueringen
          rate: cron(0 16 * * ? *)  # 16:00
          input:
            spider_name: "thueringen"

# We include files by whitelisting to reduce the deployment time.
# Just remember to add any files you create!
package:
  include:
    - launcher.py
    - jedeschule/**
    - scrapy.cfg
  exclude:
    - "./**"

plugins:
  - serverless-python-requirements
  - serverless-cloudformation-sub-variables
custom:
  pythonRequirements:
    slim: true # Omits tests, __pycache__, *.pyc etc from dependencies
    fileName: requirements.txt