name: Package with serverless

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install serverless-python-requirements
      run: serverless plugin install --name serverless-python-requirements
    - name: serverless deploy
      run: serverless deploy
      env:
        #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          .serverless
          !.serverless/requirements
